/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mobileshop.ui;

/**
 *
 * @author Iphone
 */
public class MobileRepair extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MobileRepair.class.getName());

    /**
     * Creates new form MobileRepair
     */
    public MobileRepair() {
        initComponents();
        
        this.setExtendedState(MobileRepair.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        btnSupplier = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        btnJobEntry = new javax.swing.JButton();
        btnAvailableStock = new javax.swing.JButton();
        btnBrand = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        btnSupplier.setText("Supplier Master ");
        btnSupplier.addActionListener(this::btnSupplierActionPerformed);

        btnPurchase.setText("Purchase Entry");
        btnPurchase.addActionListener(this::btnPurchaseActionPerformed);

        btnJobEntry.setText("Job Entry");
        btnJobEntry.addActionListener(this::btnJobEntryActionPerformed);

        btnAvailableStock.setText("Available Stock");
        btnAvailableStock.addActionListener(this::btnAvailableStockActionPerformed);

        btnBrand.setText("Brand");
        btnBrand.addActionListener(this::btnBrandActionPerformed);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJobEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAvailableStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnSupplier)
                .addGap(27, 27, 27)
                .addComponent(btnPurchase)
                .addGap(17, 17, 17)
                .addComponent(btnJobEntry)
                .addGap(17, 17, 17)
                .addComponent(btnAvailableStock)
                .addGap(18, 18, 18)
                .addComponent(btnBrand)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        // TODO add your handling code here:
        
        SupplierMaster suppMaster=new SupplierMaster();
        suppMaster.setVisible(true);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        BrandEntry brandEntry=new BrandEntry();
        brandEntry.setVisible(true);
    }//GEN-LAST:event_btnBrandActionPerformed

    private void btnAvailableStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableStockActionPerformed
        // TODO add your handling code here:
        AvailableStock1 availStock=new AvailableStock1();
        availStock.setVisible(true);
        
    }//GEN-LAST:event_btnAvailableStockActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        PurchaseEntry pE=new PurchaseEntry();
        pE.setVisible(true);
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnJobEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobEntryActionPerformed
        // TODO add your handling code here:
        JobSheetEntry jSEntry=new JobSheetEntry();
        jSEntry.setVisible(true);
    }//GEN-LAST:event_btnJobEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MobileRepair().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailableStock;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnJobEntry;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    // End of variables declaration//GEN-END:variables
}
