/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mobileshop.ui;

import com.mobileshop.db.DbConnection;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Iphone
 */
public class SupplierMaster extends javax.swing.JFrame {
    
    int selectedId=0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SupplierMaster.class.getName());

    /**
     * Creates new form SupplierMaster
     */
    public SupplierMaster() {
        initComponents();
        loadSupppTable();
        
    }
    
    private void loadSupppTable()
    {
        DefaultTableModel model=(DefaultTableModel)suppMasterTable.getModel();
        model.setRowCount(0);
        
        String sql="SELECT * FROM supplierMaster";
        try(Connection con=DbConnection.getConnection();
                PreparedStatement pst=con.prepareStatement(sql);
                ResultSet rs=pst.executeQuery()) {
          
            while(rs.next())
            {
                model.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6)
            });
                
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error"+ e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSuppName = new javax.swing.JTextField();
        txtSuppAddress = new javax.swing.JTextField();
        txtSuppContact = new javax.swing.JTextField();
        txtGst = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClearField = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppMasterTable = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        txtSuppShop = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Supplier Name");

        jLabel2.setText("Supplier Shop Name");

        jLabel3.setText("Supplier Address");

        jLabel4.setText("Supplier Contacts");

        jLabel5.setText("Supplier GST No");

        txtSuppContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuppContactKeyTyped(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClearField.setText("Clear Field");
        btnClearField.addActionListener(this::btnClearFieldActionPerformed);

        suppMasterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SuppId", "SuppName", "SuppShopName", "SuppAddress", "SuppContact", "SuppGst"
            }
        ));
        suppMasterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppMasterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(suppMasterTable);

        btnClose.setText("Closed");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSuppName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtSuppAddress)
                            .addComponent(txtSuppContact)
                            .addComponent(txtGst)
                            .addComponent(txtSuppShop))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClearField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSuppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSuppShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearField)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSuppAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSuppContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
       if(!emptyField())
       {
           return;
       }
       String sql = "INSERT INTO SupplierMaster(suppName, suppShopName, suppAddress, suppContact, suppGst) VALUES(?,?,?,?,?)"; 
        
    try(Connection con = DbConnection.getConnection();
        PreparedStatement pst = con.prepareStatement(sql)) {
        
        pst.setString(1, txtSuppName.getText().trim());
        pst.setString(2, txtSuppShop.getText().trim());
        pst.setString(3, txtSuppAddress.getText().trim());
        pst.setString(4, txtSuppContact.getText().trim());
        pst.setString(5, txtGst.getText().trim());
        
       int added= pst.executeUpdate();
       if(added>=0)
       {
          JOptionPane.showMessageDialog(this, "Supplier Added Successfully");
        
        loadSupppTable(); // Table refresh karo
       clearedField();       // Fields khali karo 
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Supplier Failed");
       }
    } 
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldActionPerformed
        // TODO add your handling code here:
        clearedField();
    }//GEN-LAST:event_btnClearFieldActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        upadate();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void suppMasterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppMasterTableMouseClicked
        // TODO add your handling code here:
        
         
         int row =suppMasterTable.getSelectedRow();
         selectedId=Integer.parseInt(suppMasterTable.getValueAt(row, 0).toString());
         
        if(selectedId==-1)
        {
            return;
        }
              
        DefaultTableModel model=(DefaultTableModel) suppMasterTable.getModel();
        
        txtSuppName.setText(model.getValueAt(row,1).toString());
        txtSuppShop.setText(model.getValueAt(row,2).toString());
        txtSuppAddress.setText(model.getValueAt(row,3).toString());
        txtGst.setText(model.getValueAt(row,4).toString());
        txtSuppContact.setText(model.getValueAt(row,5).toString());
    }//GEN-LAST:event_suppMasterTableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel) suppMasterTable.getModel();
        int row=suppMasterTable.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this,"plese selecte the rows");
            return;
        }
        int confirm=JOptionPane.showConfirmDialog(this,"Are you want to delect this record"+JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION)
        {
            int supId=Integer.parseInt(model.getValueAt(row,0).toString());
            String sql="DELETE FROM supplierMaster WhERE suppId=?";
            try(Connection con=DbConnection.getConnection()) {
                Statement pragmaStmt=con.createStatement();
                pragmaStmt.execute("PRAGMA foreign_keys = ON");
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setInt(1, supId);
                int delete=pst.executeUpdate();
                if(delete>0)
                {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    loadSupppTable();
                    clearedField();
                }
                
               
                
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(this,"Error"+ e.getMessage());
            }
        }
        
       
            
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
       
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSuppContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuppContactKeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        if(txtSuppContact.getText().length()>=10)
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtSuppContactKeyTyped
    
        void upadate()
        {
               
        try {
            
            if(selectedId==0)
            {
                JOptionPane.showMessageDialog(this," first select!!");
                return;
            }
       if(!emptyField())
       {
           return;
       }

        // इसके बाद तुम्हारा Update वाला SQL code...
        String sql="UPDATE  SupplierMaster SET suppName=?,suppShopName=?,suppAddress=?,suppContact=?,suppGst=? WHERE suppId=?";
        try(Connection con=DbConnection.getConnection();
                 Statement pragmaStmt = con.createStatement();){
                // Foreign Key ON karna zaroori hai update ke time bhi
       pragmaStmt.execute("PRAGMA foreign_keys = ON");
       PreparedStatement pst=con.prepareStatement(sql);
        pst.setString(1, txtSuppName.getText());
        pst.setString(2,txtSuppShop.getText());
        pst.setString(3,txtSuppAddress.getText());
        pst.setString(4,txtSuppContact.getText());
        pst.setString(5,txtGst.getText());
        pst.setInt(6,selectedId);
        
       int update= pst.executeUpdate();
       if(update>0)
       {
           JOptionPane.showMessageDialog(this, "Record update successfully");
           loadSupppTable();
           clearedField();
       }
       else{
           JOptionPane.showMessageDialog(this," update failed ");
           return;
       }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
                    
              
    void clearedField()
    {
        txtSuppName.setText("");
        txtSuppShop.setText("");
        txtSuppAddress.setText("");
        txtSuppContact.setText("");
        txtGst.setText("");
        selectedId=0;
    }
   private boolean emptyField()
    {
        if(txtSuppName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier Name cannot be empty");
            txtSuppName.requestFocus();
            return false;
        }
        if(txtSuppShop.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier Shop Name cannot be empty");
            txtSuppShop.requestFocus();
            return false;
        }
        if(txtSuppAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier Address cannot be empty");
            txtSuppAddress.requestFocus();
            return false;
        }
        if(txtSuppContact.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier Contact cannot be empty");
            txtSuppContact.requestFocus();
            return false;
        }
        if(txtGst.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier GST No cannot be empty");
            txtGst.requestFocus();
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SupplierMaster().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearField;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable suppMasterTable;
    private javax.swing.JTextField txtGst;
    private javax.swing.JTextField txtSuppAddress;
    private javax.swing.JTextField txtSuppContact;
    private javax.swing.JTextField txtSuppName;
    private javax.swing.JTextField txtSuppShop;
    // End of variables declaration//GEN-END:variables
}
